#!/bin/bash
force='-i'
if [ "$1" = "-f" ]; then
	force="-v"
fi

shopt -s dotglob globstar nullglob
GLOBIGNORE='.:..'

cd homeskel
files="**"

for file in $files; do
	homefile="$HOME/$file"
	if [[ -e $homefile ]] && [[ ! -d $homefile ]]; then
		cp -u $force $homefile $file
	fi
done
